# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout NMEA2000 library
      uses: actions/checkout@v3
      with:
          repository: ttlappalainen/NMEA2000
          ref: master
          path: CustomLibrary_NMEA2000 # must contain string "Custom"

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:m5stack-atom
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: ReactESP@2.1.0,M5Atom@0.1.0
        sketch-names: "*.ino"
        sketch-names-find-start: bbn-*/*
        extra-arduino-cli-args: "--warnings default"
        set-build-path: true

