# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout NMEA2000 library
      uses: actions/checkout@v4
      with:
          repository: ttlappalainen/NMEA2000
          ref: master
          path: CustomLibrary_NMEA2000 # must contain string "Custom"

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:m5stack-atom
        arduino-platform: esp32:esp32@2.0.17
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: ReactESP@2.1.0,M5Atom@0.1.0,M5Unit-ENV@1.2.0
        sketch-names: "*.ino"
        sketch-names-find-start: bbn-*/*
        extra-arduino-cli-args: "--warnings default"
        set-build-path: true

    - name: Merge BINs
      run: >
        pwd;
        python3 "$HOME/.arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool.py" 
        --chip esp32 merge_bin -o /home/runner/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-usb-gw-m5atom/build/bbn-nmea2000-usb-gw-m5atom-firmware.bin 
        --flash_mode dio --flash_freq 80m --flash_size 4MB 
        0x1000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-usb-gw-m5atom/build/bbn-nmea2000-usb-gw-m5atom.ino.bootloader.bin" 
        0x8000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-usb-gw-m5atom/build/bbn-nmea2000-usb-gw-m5atom.ino.partitions.bin" 
        0xe000 "$HOME/.arduino15/packages/esp32/hardware/esp32/2.0.17/tools/partitions/boot_app0.bin" 
        0x10000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-usb-gw-m5atom/build/bbn-nmea2000-usb-gw-m5atom.ino.bin"; 
        python3 "$HOME/.arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool.py" 
        --chip esp32 merge_bin -o /home/runner/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-env-m5atom/build/bbn-nmea2000-env-m5atom-firmware.bin 
        --flash_mode dio --flash_freq 80m --flash_size 4MB 
        0x1000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-env-m5atom/build/bbn-nmea2000-env-m5atom.ino.bootloader.bin" 
        0x8000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-env-m5atom/build/bbn-nmea2000-env-m5atom.ino.partitions.bin" 
        0xe000 "$HOME/.arduino15/packages/esp32/hardware/esp32/2.0.17/tools/partitions/boot_app0.bin" 
        0x10000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-env-m5atom/build/bbn-nmea2000-env-m5atom.ino.bin"; 
        python3 "$HOME/.arduino15/packages/esp32/tools/esptool_py/4.5.1/esptool.py" 
        --chip esp32 merge_bin -o /home/runner/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-att-m5atom/build/bbn-nmea2000-att-m5atom-firmware.bin 
        --flash_mode dio --flash_freq 80m --flash_size 4MB 
        0x1000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-att-m5atom/build/bbn-nmea2000-att-m5atom.ino.bootloader.bin" 
        0x8000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-att-m5atom/build/bbn-nmea2000-att-m5atom.ino.partitions.bin" 
        0xe000 "$HOME/.arduino15/packages/esp32/hardware/esp32/2.0.17/tools/partitions/boot_app0.bin" 
        0x10000 "$HOME/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/bbn-nmea2000-att-m5atom/build/bbn-nmea2000-att-m5atom.ino.bin"
        
    - name: Make zip
      run: |
        ls /home/runner/work/bbn-nmea200-m5atom/bbn-nmea200-m5atom/*/build/*.bin | zip bbn-nmea200-m5atom_bin-$(date +%Y-%m-%d).zip -j -@
        pwd
        ls *.zip

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bbn-nmea200-m5atom_bin*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
